JOINTS_24 = [  # SMPL-24 Skeleton 24 joints
    "Pelvis",
    "LHip",
    "RHip",
    "Spine1",
    "LKnee",
    "RKnee",
    "Spine2",
    "LAnkle",
    "RAnkle",
    "Spine3",
    "LFoot",
    "RFoot",
    "Neck",
    "LCollar",
    "RCollar",
    "Head",
    "LShoulder",
    "RShoulder",
    "LElbow",
    "RElbow",
    "LWrist",
    "RWrist",
    "LHand",
    "RHand",
]
BONES_24_NAMES = [
    ("Pelvis", "LHip"),
    ("Pelvis", "RHip"),
    ("Pelvis", "Spine1"),
    ("LHip", "LKnee"),
    ("RHip", "RKnee"),
    ("Spine1", "Spine2"),
    ("LKnee", "LAnkle"),
    ("RKnee", "RAnkle"),
    ("Spine2", "Spine3"),
    ("LAnkle", "LFoot"),
    ("RAnkle", "RFoot"),
    ("Spine3", "Neck"),
    ("Spine3", "LCollar"),
    ("Spine3", "RCollar"),
    ("Neck", "Head"),
    ("LCollar", "LShoulder"),
    ("RCollar", "RShoulder"),
    ("LShoulder", "LElbow"),
    ("RShoulder", "RElbow"),
    ("LElbow", "LWrist"),
    ("RElbow", "RWrist"),
    ("LWrist", "LHand"),
    ("RWrist", "RHand"),
]

BONES_24_INDS = [(JOINTS_24.index(e[0]), JOINTS_24.index(e[1])) for e in BONES_24_NAMES]
